Repository SciTools/cartopy, pull requests merged in 2018-10, with the labels that each got.

#1124 ENH: Support proj4 v5+
  .travis.yml
  INSTALL
  lib/cartopy/_crs.pxd
  lib/cartopy/_crs.pyx
  lib/cartopy/crs.py
  lib/cartopy/geodesic/_geodesic.pyx
  lib/cartopy/tests/crs/test_mercator.py
  lib/cartopy/tests/crs/test_miller.py
  lib/cartopy/tests/crs/test_mollweide.py
  lib/cartopy/tests/crs/test_robinson.py
  lib/cartopy/tests/crs/test_stereographic.py
  lib/cartopy/tests/crs/test_transverse_mercator.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/multiple_projections5.png
  lib/cartopy/tests/mpl/test_images.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
  lib/cartopy/tests/mpl/test_web_services.py
  lib/cartopy/tests/test_crs.py
  lib/cartopy/tests/test_img_tiles.py
  lib/cartopy/trace.pyx
  setup.py
Labels: Component: proj, Type: Enhancement

#1148 Fuzz more projection boundaries to work with proj >= 5
  lib/cartopy/crs.py
  lib/cartopy/tests/crs/test_albers_equal_area.py
  lib/cartopy/tests/crs/test_interrupted_goode_homolosine.py
  lib/cartopy/tests/crs/test_sinusoidal.py
Labels: Component: proj, Type: Enhancement

#1146 Fix projected line strings getting truncated early.
  lib/cartopy/_trace.cpp
  lib/cartopy/tests/test_polygon.py
Labels: Component: Geometry transforms, Type: Bug

#1158 TST: Update web tiles result image.
  lib/cartopy/tests/mpl/baseline_images/mpl/test_images/web_tiles.png
Labels: Type: Bug

#1022 Add support for Equidistant Conic projection.
  docs/make_projection.py
  docs/source/crs/projections.rst
  lib/cartopy/crs.py
  lib/cartopy/tests/crs/test_equidistant_conic.py
Labels: Component: proj, SemVer: minor, Type: Enhancement

#1159 TST: Allow new test images to use any mpl style.
  lib/cartopy/tests/mpl/__init__.py
Labels: Component: matplotlib

#1160 Use both x/y limits to determine Mercator threshold.
  lib/cartopy/crs.py
  lib/cartopy/tests/mpl/test_set_extent.py
Labels: Type: Bug

#1132 BLD: Add pyproject.toml defining build requirements.
  MANIFEST.in
  pyproject.toml
  setup.py
Labels: Component: installation, Type: Enhancement

#1153 Update sphinx-gallery to 0.2.0
  docs/doc-requirements.txt
  docs/source/conf.py
  docs/source/sphinxext/pre_sphinx_gallery.py
Labels: Type: Documentation
