Repository SciTools/cartopy, pull requests merged in 2018-11, with the labels that each got.

#1163 Add Travis configuration to upload sdists to PyPI
  .travis.yml
Labels: Type: Infrastructure

#1169 Improve docs for Cython extensions
  INSTALL
  docs/source/cartopy/geodesic.rst
  docs/source/cartopy/trace.rst
  docs/source/conf.py
  docs/source/crs/index.rst
  docs/source/index.rst
  lib/cartopy/_crs.pyx
  lib/cartopy/geodesic/__init__.py
  lib/cartopy/geodesic/_geodesic.pyx
  lib/cartopy/trace.pyx
Labels: Type: Documentation

#1173 Add links to the Gitter chatroom
  README.md
  docs/source/index.rst
Labels: Type: Documentation

#1130 Fix support for Matplotlib 3.0.0
  .travis.yml
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/global_contour_wrap.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/global_contour_wrap_mpl_pre_3.0.0.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/streamplot_mpl_2.0.0.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/streamplot_mpl_2.1.0.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/streamplot_mpl_3.0.0.png
  lib/cartopy/tests/mpl/test_mpl_integration.py
Labels: Component: matplotlib

#1168 Add Eckert family of projections
  INSTALL
  docs/make_projection.py
  docs/source/crs/projections.rst
  lib/cartopy/crs.py
  lib/cartopy/tests/crs/test_eckert.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/multiple_projections1.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/multiple_projections4.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/multiple_projections5.png
  lib/cartopy/tests/mpl/test_mpl_integration.py
Labels: Type: Enhancement

#1162 Stop guessing whether Paths are polygons on new MPL.
  lib/cartopy/mpl/patch.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_features/gshhs_coastlines.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/natural_earth_interface.png
  lib/cartopy/tests/mpl/test_patch.py
Labels: Component: Geometry transforms

#1180 Improve warped rectangular projections
  lib/cartopy/crs.py
  lib/cartopy/tests/crs/test_eckert.py
  lib/cartopy/tests/crs/test_mollweide.py
  lib/cartopy/tests/crs/test_robinson.py
  lib/cartopy/tests/test_crs.py
Labels: Type: Documentation, Type: Enhancement

#1019 Added the styler keyword to allow on-demand / callback to determine styling of geometries in the matplotlib interface.
  lib/cartopy/examples/hurricane_katrina.py
  lib/cartopy/mpl/feature_artist.py
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/test_axes.py
  lib/cartopy/tests/mpl/test_feature_artist.py
Labels: Component: matplotlib, SemVer: minor, Type: Enhancement

#1195 Add raster caching to smooth pan/zoom
  lib/cartopy/mpl/slippy_image_artist.py
Labels: Component: matplotlib, SemVer: minor, Type: Enhancement

#1197 SlippyImageArtist redraw on mouse down
  lib/cartopy/mpl/slippy_image_artist.py
Labels: Component: matplotlib, Type: Bug

#1196 Add pretty Jupyter repr of Projections
  lib/cartopy/crs.py
Labels: Component: matplotlib, SemVer: minor, Type: Enhancement

#951 Add _repr_html_ to Projection class
  lib/cartopy/crs.py
Labels: Experience-needed: low, SemVer: minor, Type: Enhancement

#1029 Better support colour overrides for Features.
  lib/cartopy/mpl/feature_artist.py
Labels: Component: matplotlib, SemVer: minor, Type: Enhancement

#1201 Make nightshade example figure size consistent.
  lib/cartopy/examples/nightshade.py
Labels: Type: Documentation

#1203 Fix pypi deploy
  .travis.yml
Labels: Type: Infrastructure

#1211 TST: Update Natural Earth pytest markers.
  lib/cartopy/tests/mpl/test_nightshade.py
  lib/cartopy/tests/test_shapereader.py
Labels: Type: Bug

#1208 Add desired_tile_form to Stamen.
  lib/cartopy/io/img_tiles.py
Labels: Component: Raster source, Type: Bug

#1218 DOC: Fix some minor issues
  docs/source/_static/version_switch.js
  docs/source/_templates/layout.html
Labels: Type: Bug, Type: Documentation

#1216 Fix Geostationary projection boundary
  lib/cartopy/crs.py
  lib/cartopy/tests/crs/test_geostationary.py
Labels: Component: proj, Type: Bug

#1220 Replace some GEOS with pure math in straightAndDomain
  lib/cartopy/_trace.cpp
Labels: Component: Geometry transforms

#1219 Use proj geodesic functions for spherical interpolation.
  lib/cartopy/_trace.cpp
  lib/cartopy/_trace.h
  lib/cartopy/tests/mpl/baseline_images/mpl/test_examples/global_map.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/global_map.png
Labels: Component: Geometry transforms, Component: proj, Type: Enhancement

#1213 Turn GeoAxes.outline_patch into a GeoSpine.
  lib/cartopy/examples/effects_of_the_ellipse.py
  lib/cartopy/examples/hurricane_katrina.py
  lib/cartopy/examples/un_flag.py
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/mpl/slippy_image_artist.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/global_contour_wrap.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/streamplot_mpl_3.0.0.png
  lib/cartopy/tests/mpl/test_img_transform.py
Labels: Component: matplotlib, Type: Bug, Type: Enhancement

#1222 Test against oldest Cython.
  .travis.yml
  INSTALL
  pyproject.toml
  setup.py
Labels: Type: Infrastructure
