Repository SciTools/cartopy, pull requests merged in 2018-12, with the labels that each got.

#1227 Add support for CompoundCRS
  INSTALL
  lib/cartopy/_epsg.py
  lib/cartopy/tests/test_crs.py
  requirements/epsg.txt
Labels: SemVer: minor, Type: Enhancement

#1190 Implement cartopy.mpl.style for matplotlib style composition
  lib/cartopy/feature/__init__.py
  lib/cartopy/mpl/feature_artist.py
  lib/cartopy/mpl/style.py
  lib/cartopy/tests/mpl/test_feature_artist.py
  lib/cartopy/tests/mpl/test_style.py
Labels: Component: matplotlib, Experience-needed: medium, SemVer: minor, Type: Bug, Type: Enhancement

#1224 Enable appveyor builds
  .appveyor.yml
  lib/cartopy/io/img_nest.py
  lib/cartopy/tests/test_coding_standards.py
  lib/cartopy/tests/test_img_nest.py
  setup.py
Labels: Type: Enhancement, Type: Infrastructure

#1234 Ensure boundary paths are always closed.
  lib/cartopy/crs.py
  lib/cartopy/mpl/patch.py
Labels: Component: Gridlines, Component: matplotlib, Type: Bug

#1228 Update #1061 to use latest pyshp.
  INSTALL
  lib/cartopy/io/shapereader.py
Labels: SemVer: minor, Type: Enhancement

#1238 Remove unnecessary use of FigureCanvasAgg.
  lib/cartopy/tests/mpl/test_gridliner.py
Labels: Component: matplotlib

#1232 Made image tile fetching multi-threaded
  .appveyor.yml
  .circleci/config.yml
  .travis.yml
  lib/cartopy/io/img_tiles.py
  requirements/default.txt
Labels: Component: Raster source, SemVer: minor, Type: Enhancement

#1236 Add python_requires to help pip
  setup.py
Labels: Blocked: CLA needed
