Repository SciTools/cartopy, pull requests merged in 2018-04, with the labels that each got.

#1054 DOC: change natural_earth to shapereader.natural_earth in example
  lib/cartopy/io/shapereader.py
Labels: Experience-needed: low, Type: Documentation

#1037 Add ne_ prefix to NaturalEarth cache files.
  lib/cartopy/io/shapereader.py
Labels: SemVer: minor

#1041 Drop support for Matplotlib < 1.5.1 and NumPy < 1.10
  .travis.yml
  INSTALL
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/mpl/patch.py
  lib/cartopy/tests/mpl/__init__.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_gridliner/gridliner_labels_pre_mpl_1.5.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/global_pcolor_wrap_pre_mpl_1.4.3.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/streamplot_pre_mpl_1.4.3.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_shapely_to_mpl/poly_interiors_pre_mpl_1.5.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/xticks_cylindrical_pre_mpl_1.5.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/xyticks_pre_mpl_1.5.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/yticks_cylindrical_pre_mpl_1.5.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/yticks_no_transform_pre_mpl_1.5.png
  lib/cartopy/tests/mpl/test_gridliner.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
  lib/cartopy/tests/mpl/test_shapely_to_mpl.py
  lib/cartopy/tests/mpl/test_ticks.py
  requirements/default.txt
  requirements/plotting.txt
  setup.py
Labels: Component: matplotlib, SemVer: minor, Type: Infrastructure

#1063 DOC: Update conda to try to fix circleci.
  .circleci/config.yml
Labels: Type: Documentation, Type: Infrastructure
