Repository SciTools/cartopy, pull requests merged in 2018-07, with the labels that each got.

#1042 Normalize grid coordinates used for interpolation.
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/barbs_regrid.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/quiver_regrid.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/streamplot.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/streamplot_mpl_1.4.3.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/streamplot_mpl_2.png
  lib/cartopy/vector_transform.py
Labels: Type: Bug

#1070 Update image tests for matplotlib 2.1.
  .gitignore
  .travis.yml
  MANIFEST.in
  lib/cartopy/io/shapereader.py
  lib/cartopy/tests/lakes_shapefile/ne_110m_lakes.dbf
  lib/cartopy/tests/lakes_shapefile/ne_110m_lakes.shp
  lib/cartopy/tests/lakes_shapefile/ne_110m_lakes.shx
  lib/cartopy/tests/mpl/baseline_images/mpl/test_gridliner/gridliner_labels.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_images/web_tiles.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/xticks_cylindrical.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/xticks_no_transform.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/xyticks.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/yticks_cylindrical.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/yticks_no_transform.png
  lib/cartopy/tests/mpl/test_images.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
  lib/cartopy/tests/mpl/test_ticks.py
  lib/cartopy/tests/test_crs.py
  lib/cartopy/tests/test_shapereader.py
  setup.cfg
  setup.py
Labels: Component: matplotlib, Type: Infrastructure

#1062 Fix transform_points for empty arrays
  .gitignore
  lib/cartopy/_crs.pyx
  lib/cartopy/tests/mpl/test_plots.py
Labels: Component: proj, Type: Bug

#1000 Creating a Fiona Reader for shapefiles
  INSTALL
  docs/source/contributors.rst
  docs/source/whats_new.rst
  lib/cartopy/crs.py
  lib/cartopy/io/shapereader.py
Labels: SemVer: minor, Type: Enhancement

#1043 Add more options to Mercator projection
  lib/cartopy/crs.py
  lib/cartopy/tests/crs/test_mercator.py
Labels: Component: proj, Type: Enhancement

#1075 conda list --explicit
  .travis.yml
Labels: Type: Infrastructure

#1069 Make use of README.md in setup.py, and update README.md to include some badges and an image
  README.md
  README.rst
  setup.py
Labels: Type: Documentation
