Repository SciTools/cartopy, pull requests merged in 2019-01, with the labels that each got.

#1264 Always use cythonized files in sdist.
  .appveyor.yml
  .travis.yml
  INSTALL
  MANIFEST.in
  lib/cartopy/trace.pyx
  pyproject.toml
  setup.py
Labels: Component: installation, Type: Infrastructure

#1268 Fix some warnings in tests
  lib/cartopy/crs.py
  lib/cartopy/tests/crs/test_lambert_conformal.py
  lib/cartopy/tests/io/test_ogc_clients.py
  lib/cartopy/tests/io/test_srtm.py
  lib/cartopy/tests/mpl/test_ticker.py
Labels: Type: Bug

#1259 Remove the shapely_from_geos performance workaround
  lib/cartopy/trace.pyx
Labels: SemVer: minor, Type: Bug

#1271 Add coverage reporting.
  .coveragerc
  .travis.yml
  setup.py
Labels: Type: Infrastructure
