Repository SciTools/cartopy, pull requests merged in 2020-04, with the labels that each got.

#1452 Fix file paths for coverage on coveralls.
  .coveragerc
  .travis.yml
Labels: Type: Infrastructure

#1422 Move GeoAxes.background_patch to GeoAxes.patch.
  lib/cartopy/examples/favicon.py
  lib/cartopy/examples/hurricane_katrina.py
  lib/cartopy/examples/un_flag.py
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/mpl/gridliner.py
  lib/cartopy/mpl/slippy_image_artist.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_examples/contour_label.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/pcolormesh_goode_wrap.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_nightshade/nightshade_platecarree.png
  lib/cartopy/tests/mpl/test_examples.py
  lib/cartopy/tests/mpl/test_features.py
  lib/cartopy/tests/mpl/test_gridliner.py
  lib/cartopy/tests/mpl/test_images.py
  lib/cartopy/tests/mpl/test_img_transform.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
  lib/cartopy/tests/mpl/test_pseudo_color.py
  lib/cartopy/tests/mpl/test_shapely_to_mpl.py
  lib/cartopy/tests/mpl/test_web_services.py
Labels: Component: matplotlib, Type: Bug, Type: Enhancement

#1513 Fix contourf crash with empty collection.
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/test_contour.py
Labels: Component: matplotlib

#1515 Remove unused HeaderCheck from setup.py.
  setup.py
Labels: Type: Infrastructure

#1519 Update what's new for 0.18
  docs/source/whats_new.rst
Labels: Type: Documentation

#1514 Ensure raster sources work with tight layout
  lib/cartopy/mpl/slippy_image_artist.py
  lib/cartopy/tests/mpl/test_web_services.py
Labels: Component: Raster source, Component: matplotlib, Type: Bug

#1520 Fix mesh_projection when an extent is 0.
  lib/cartopy/img_transform.py
  lib/cartopy/tests/test_img_transform.py
Labels: Component: Geometry transforms, Component: Raster source, Type: Bug

#1523 DOC: Increase timeout for install step on CircleCI.
  .circleci/config.yml
Labels: Type: Documentation, Type: Infrastructure

#1535 Clip inline gridline labels
  lib/cartopy/mpl/gridliner.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_gridliner/gridliner_labels_inline_usa.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_gridliner/gridliner_labels_inline_usa_1.5.png
Labels: Component: Gridlines, Component: matplotlib

#1529 Add gridliner/ticklabels example to the gallery
  lib/cartopy/examples/gridliner.py
Labels: Component: Gridlines, Type: Documentation

#1536 Drop Python 2 doc builds on CI
  .circleci/config.yml
Labels: Type: Infrastructure

#1516 Remove support for Python 2
  .appveyor.yml
  .stickler.yml
  .travis.yml
  INSTALL
  docs/source/index.rst
  requirements/default.txt
  setup.py
Labels: Component: installation, Type: Enhancement, Type: Infrastructure

#1517 Remove six.
  INSTALL
  lib/cartopy/_crs.pyx
  lib/cartopy/crs.py
  lib/cartopy/feature/__init__.py
  lib/cartopy/io/__init__.py
  lib/cartopy/io/img_nest.py
  lib/cartopy/io/img_tiles.py
  lib/cartopy/io/ogc_clients.py
  lib/cartopy/io/shapereader.py
  lib/cartopy/io/srtm.py
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/mpl/style.py
  lib/cartopy/sphinxext/summarise_package.py
  lib/cartopy/tests/io/test_srtm.py
  lib/cartopy/tests/mpl/test_caching.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
  lib/cartopy/tests/test_img_nest.py
  requirements/default.txt
Labels: Type: Infrastructure
