Repository SciTools/cartopy, pull requests merged in 2020-07, with the labels that each got.

#1582 Fix for RGBA array
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/test_images.py
Labels: Type: Bug

#1255 Improved the testability of trace.
  lib/cartopy/trace.pyx
Labels: Component: Geometry transforms, SemVer: minor, Type: Enhancement

#1545 Switch to setuptools-scm instead of versioneer.
  .appveyor.yml
  .circleci/config.yml
  .git_archival.txt
  .gitattributes
  .gitignore
  .travis.yml
  MANIFEST.in
  lib/cartopy/__init__.py
  lib/cartopy/_version.py
  lib/cartopy/tests/test_coding_standards.py
  setup.cfg
  setup.py
  versioneer.py
Labels: Type: Infrastructure

#1593 Add example with label only on top and left sides
  lib/cartopy/examples/gridliner.py
Labels: Type: Documentation
