Repository SciTools/cartopy, pull requests merged in 2020-12, with the labels that each got.

#1669 feature: its now possible to add bbox style on labels
  lib/cartopy/mpl/gridliner.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_gridliner/gridliner_labels_bbox_style.png
  lib/cartopy/tests/mpl/test_gridliner.py
Labels: Component: Gridlines, Type: Enhancement

#1681 restore PEP-517 support
  .travis.yml
  INSTALL
  pyproject.toml
  requirements/default.txt
  setup.py
Labels: Component: installation

#1672 change hemisphere location i gridlines labels.
  lib/cartopy/mpl/ticker.py
  lib/cartopy/tests/mpl/test_ticker.py
Labels: Component: Gridlines

#1686 add python 3.9 support
  .travis.yml
  setup.py
Labels: Component: installation, Type: Documentation
