Repository SciTools/cartopy, pull requests merged in 2020-11, with the labels that each got.

#1662 Add option to remove 'E', 'W', 'N', 'S' from axis labels. Fixes #1635
  lib/cartopy/mpl/ticker.py
  lib/cartopy/tests/mpl/test_ticker.py
Labels: Component: Gridlines, Type: Enhancement

#1636 Changing the interpolation of vectors into the source projection
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/barbs_regrid.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/quiver_regrid.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/streamplot_mpl_2.1.0.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/streamplot_mpl_2.2.2.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/streamplot_mpl_3.2.0.png
  lib/cartopy/tests/mpl/test_mpl_integration.py
  lib/cartopy/tests/test_vector_transform.py
  lib/cartopy/vector_transform.py
Labels: Component: Geometry transforms

#1533 Add simple cache mechanism to GoogleWTS class
  lib/cartopy/__init__.py
  lib/cartopy/io/img_tiles.py
  lib/cartopy/tests/test_img_tiles.py
Labels: Type: Enhancement
