Repository SciTools/cartopy, pull requests merged in 2020-08, with the labels that each got.

#1612 Don't use `_shp`-suffixed Natural Earth files.
  lib/cartopy/examples/hurricane_katrina.py
  tools/feature_download.py
Labels: Component: Feature source

#1611 BUG: Fix lines with >1000 points disappearing (Fixes #1442)
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_axes/geoaxes_subslice.png
  lib/cartopy/tests/mpl/test_axes.py
Labels: Component: matplotlib

#1629 Filter warnings that we can expect
  lib/cartopy/tests/io/test_ogc_clients.py
  lib/cartopy/tests/mpl/test_caching.py
  lib/cartopy/tests/mpl/test_features.py
  lib/cartopy/tests/mpl/test_web_services.py
  lib/cartopy/tests/test_coastline.py
  lib/cartopy/tests/test_shapereader.py
Labels: Type: Infrastructure

#1628 Adding an autouse fixture to close plots after each test
  lib/cartopy/tests/mpl/conftest.py
Labels: Type: Infrastructure

#1622 Pcolormesh wrapping fix
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
Labels: Component: matplotlib

#1637 Remove mock dependency.
  INSTALL
  requirements/tests.txt
Labels: Component: installation, Low hanging fruit
