Repository SciTools/cartopy, pull requests merged in 2020-03, with the labels that each got.

#1105 Utilise AdaptiveScalar in default NaturalEarthFeatures
  lib/cartopy/feature/__init__.py
  lib/cartopy/mpl/feature_artist.py
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/test_gridliner.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
  lib/cartopy/tests/mpl/test_shapely_to_mpl.py
Labels: Component: Feature source, Experience-needed: medium, SemVer: minor, Type: Enhancement

#1485 Update CircleCI config
  .circleci/config.yml
  .github/workflows/circleci.yml
Labels: Type: Documentation, Type: Infrastructure

#1491 Fix pickle/deepcopy for non-default argument CRSs
  lib/cartopy/_crs.pyx
  lib/cartopy/tests/test_crs.py
  setup.py
Labels: Component: proj, SemVer: patch, Type: Bug
