Repository SciTools/cartopy, pull requests merged in 2020-02, with the labels that each got.

#1455 Revert changes to licensing files.
  COPYING
  COPYING.LESSER
  README.md
  lib/cartopy/__init__.py
  lib/cartopy/tests/test_coding_standards.py
Labels: Type: Bug

#1440 Adding a bounds check to imshow fast path.
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/test_images.py
Labels: Component: Geometry transforms, Component: matplotlib, Type: Bug

#1424 Followup to #1117
  lib/cartopy/examples/un_flag.py
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/mpl/gridliner.py
  lib/cartopy/mpl/ticker.py
Labels: Component: Gridlines, Type: Bug, Type: Documentation

#1454 Make using tox a bit easier
  lib/cartopy/tests/conftest.py
  setup.cfg
  setup.py
Labels: Component: installation

#1469 Fix tests for Proj 6.3
  lib/cartopy/tests/crs/test_robinson.py
Labels: Component: proj, Type: Bug
