Repository SciTools/cartopy, pull requests merged in 2021-12, with the labels that each got.

#1962 MNT: Update the natural earth test
  lib/cartopy/tests/mpl/baseline_images/mpl/test_features/natural_earth.png
  lib/cartopy/tests/mpl/test_features.py
Labels: Type: Infrastructure, Component: Feature source

#1964 Parametrize projection test images
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/global_map.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/multiple_projections5.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/multiple_projections520.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_EckertI.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_EckertII.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_EckertIII.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_EckertIV.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_EckertV.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_EckertVI.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_EqualEarth.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_Gnomonic.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_InterruptedGoodeHomolosine.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_LambertCylindrical.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_Mercator.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_Miller.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_Mollweide.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_NorthPolarStereo.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_OSGB.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_Orthographic.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_PlateCarree.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_Robinson.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_RotatedPole.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_SouthPolarStereo.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_Stereographic.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_TransverseMercator.png
  lib/cartopy/tests/mpl/test_mpl_integration.py
Labels: Component: matplotlib

#1976 Rename master branch to main
  INSTALL
  README.md
  benchmarks/asv.conf.json
  docs/source/conf.py
Labels: Type: Infrastructure
