Repository SciTools/cartopy, pull requests merged in 2021-09, with the labels that each got.

#1784 FIX: Don't reset datalims in contour, only update/expand
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/test_contour.py
Labels: Type: Bug, Component: matplotlib

#1841 MPL 35 tolerance increases
  lib/cartopy/tests/mpl/test_examples.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
Labels: Component: matplotlib, Type: Infrastructure

#1840 MNT: Update Feature Artist default zorder
  docs/source/reference/feature.rst
  lib/cartopy/mpl/feature_artist.py
Labels: Type: Infrastructure, Component: Feature source

#1853 Bump minimum Pytest to 5.1.2
  INSTALL
  lib/cartopy/tests/io/test_downloaders.py
  lib/cartopy/tests/mpl/test_set_extent.py
  lib/cartopy/tests/test_img_nest.py
  lib/cartopy/tests/test_img_tiles.py
  requirements/tests.txt
Labels: Type: Infrastructure, Component: installation

#1852 Bump minimum Matplotlib to 3.1
  INSTALL
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/mpl/patch.py
  lib/cartopy/mpl/slippy_image_artist.py
  lib/cartopy/tests/mpl/test_gridliner.py
  lib/cartopy/tests/mpl/test_patch.py
  requirements/plotting.txt
Labels: Component: matplotlib, Type: Infrastructure, Component: installation

#1851 Bump minimum NumPy to 1.18
  lib/cartopy/util.py
  requirements/default.txt
Labels: Type: Infrastructure, Component: installation

#1856 Bump remaining deps to follow NEP29
  INSTALL
  lib/cartopy/img_transform.py
  lib/cartopy/tests/io/test_ogc_clients.py
  pyproject.toml
  requirements/default.txt
  requirements/ows.txt
  requirements/plotting.txt
  setup.py
Labels: Type: Infrastructure, Component: installation

#1847 BUG: Fix pcolormesh with nan inputs and wrapping
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
Labels: Type: Bug, Component: matplotlib

#1857 Port Geodesic class to pyproj
  lib/cartopy/geodesic.py
  lib/cartopy/geodesic/__init__.py
  lib/cartopy/geodesic/_geodesic.pxd
  lib/cartopy/tests/test_geodesic.py
  lib/cartopy/trace.pyx
  setup.py
Labels: Component: Geometry transforms, Component: proj

#1866 DOC: Updating installation markdown
  INSTALL
Labels: Type: Documentation

#1871 DOC: Remove mention of block plot
  docs/source/matplotlib/intro.rst
Labels: Type: Documentation

#1854 Bump minimum Proj to 8.0.0
  .circleci/config.yml
  lib/cartopy/crs.py
  lib/cartopy/tests/crs/test_equal_earth.py
  lib/cartopy/tests/crs/test_interrupted_goode_homolosine.py
  lib/cartopy/tests/crs/test_orthographic.py
  lib/cartopy/tests/crs/test_robinson.py
  lib/cartopy/tests/crs/test_transverse_mercator.py
  lib/cartopy/tests/mpl/test_crs.py
  lib/cartopy/tests/mpl/test_gridliner.py
  lib/cartopy/tests/mpl/test_images.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
  lib/cartopy/tests/mpl/test_web_services.py
  lib/cartopy/tests/test_crs.py
  lib/cartopy/tests/test_img_tiles.py
  lib/cartopy/trace.pyx
  setup.py
Labels: Component: proj, Type: Infrastructure

#1690 ENH: Adding a contour fast-path to speed up contouring
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/test_contour.py
Labels: Type: Enhancement, Component: matplotlib, Component: Geometry transforms

#1843 Use packaging.version instead of distutils
  docs/source/conf.py
  lib/cartopy/tests/mpl/__init__.py
  lib/cartopy/tests/mpl/test_examples.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
  requirements/tests.txt
Labels: Type: Infrastructure

#1874 Dedent some gridline code
  lib/cartopy/mpl/gridliner.py
Labels: Component: Gridlines

#1877 Improve gridline labels slightly
  lib/cartopy/mpl/gridliner.py
Labels: Component: Gridlines

#1875 DOC: Add an example using the transform_first keyword argument
  examples/scalar_data/contour_transforms.py
Labels: Type: Documentation

#1646 Pcolormesh update for interpolation with wrapped coordinates
  lib/cartopy/crs.py
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
  lib/cartopy/tests/mpl/test_pseudo_color.py
Labels: Type: Bug, Component: matplotlib, Type: Infrastructure

#1882 Regenerate all tick test images
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/xticks_cylindrical.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/xticks_no_transform.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/xyticks.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/yticks_cylindrical.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_ticks/yticks_no_transform.png
  lib/cartopy/tests/mpl/test_ticks.py
Labels: Component: matplotlib
