Repository SciTools/cartopy, pull requests merged in 2021-03, with the labels that each got.

#1710 Transform points
  lib/cartopy/_crs.pyx
  lib/cartopy/tests/test_crs.py
Labels: Component: Geometry transforms, Component: proj

#1724 Skipping bad GEOS version and updating Appveyor Python version
  .appveyor.yml
  lib/cartopy/tests/mpl/test_gridliner.py
Labels: Type: Infrastructure

#1742 ci: Don't allow proj 8 yet
  .appveyor.yml
  .circleci/config.yml
  .github/workflows/ci-testing.yml
  .github/workflows/circleci.yml
  .github/workflows/release.yml
Labels: Component: proj, Type: Infrastructure
