Repository SciTools/cartopy, pull requests merged in 2022-09, with the labels that each got.

#2075 TST: Update test path search and pytest deprecations
  lib/cartopy/tests/mpl/test_style.py
  setup.cfg
Labels: Type: Infrastructure

#1998 FIX: Allow values less than -180 to be wrapped too
  lib/cartopy/crs.py
  lib/cartopy/tests/test_crs.py
  lib/cartopy/trace.pyx
Labels: Component: Geometry transforms

#2074 DOC: What's new for v0.21 release
  .circleci/config.yml
  .github/workflows/ci-testing.yml
  .github/workflows/release.yml
  INSTALL
  docs/source/conf.py
  docs/source/whatsnew/index.rst
  docs/source/whatsnew/v0.21.rst
  environment.yml
  requirements/default.txt
Labels: Type: Documentation

#1249 Add Matplotlib geo projections
  docs/source/reference/projections.rst
  lib/cartopy/crs.py
  lib/cartopy/tests/crs/test_aitoff.py
  lib/cartopy/tests/crs/test_hammer.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_Aitoff.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_Hammer.png
  lib/cartopy/tests/mpl/test_mpl_integration.py
Labels: Type: Enhancement, Component: Geometry transforms
