Repository SciTools/cartopy, pull requests merged in 2023-11, with the labels that each got.

#2273 MNT: Use ruff for formatting checks
  .pre-commit-config.yaml
  environment.yml
  examples/miscellanea/eccentric_ellipse.py
  lib/cartopy/feature/nightshade.py
  lib/cartopy/io/img_nest.py
  lib/cartopy/io/img_tiles.py
  lib/cartopy/io/ogc_clients.py
  lib/cartopy/mpl/gridliner.py
  lib/cartopy/tests/io/test_ogc_clients.py
  lib/cartopy/tests/io/test_srtm.py
  lib/cartopy/tests/mpl/test_gridliner.py
  lib/cartopy/tests/mpl/test_images.py
  lib/cartopy/tests/mpl/test_ticker.py
  lib/cartopy/tests/test_crs.py
  lib/cartopy/tests/test_img_nest.py
  pyproject.toml
Labels: Type: Infrastructure

#2287 DOC: fix LAND zorder in feature example
  examples/lines_and_polygons/feature_creation.py
Labels: Type: Documentation

#2283 FIX: Handle non-earth bodies within Projections
  lib/cartopy/crs.py
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/mpl/ticker.py
  lib/cartopy/tests/crs/test_lambert_conformal.py
  lib/cartopy/tests/mpl/test_gridliner.py
  lib/cartopy/tests/mpl/test_ticker.py
Labels: Component: Gridlines
