Repository SciTools/cartopy, pull requests merged in 2023-10, with the labels that each got.

#2249 Make GridLiner into an Artist
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/mpl/gridliner.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_gridliner/gridliner_labels_title_adjust.png
  lib/cartopy/tests/mpl/conftest.py
  lib/cartopy/tests/mpl/test_gridliner.py
Labels: Component: Gridlines

#2267 MNT: Update gitignore items
  .gitignore
Labels: Type: Infrastructure

#2264 Add xfails to current owslib failures
  docs/source/conf.py
  examples/miscellanea/eccentric_ellipse.py
  lib/cartopy/tests/io/test_ogc_clients.py
  lib/cartopy/tests/mpl/test_caching.py
  lib/cartopy/tests/mpl/test_web_services.py
Labels: Type: Infrastructure

#2265 DOC: Change Stamen image tiles over to Google
  examples/lines_and_polygons/effects_of_the_ellipse.py
  examples/scalar_data/eyja_volcano.py
  examples/web_services/image_tiles.py
Labels: Type: Documentation

#2272 MNT: Add Python 3.12 to the tests and enable release testing
  .github/workflows/ci-testing.yml
  .github/workflows/release.yml
  pyproject.toml
Labels: CI: build wheels

#2262 FIX: Handle invalid geometries for rectangular projections
  lib/cartopy/tests/test_line_string.py
  lib/cartopy/trace.pyx
Labels: Type: Bug, Component: Geometry transforms

#2269 ENH: Add Stadia Maps image tile server class
  docs/source/reference/io.rst
  lib/cartopy/io/img_tiles.py
  lib/cartopy/tests/test_img_tiles.py
Labels: Component: Raster source

#2274 MNT: Remove beautifulsoup4 from docs requirements
  docs/doc-requirements.txt
  environment.yml
  pyproject.toml
Labels: Type: Documentation, Component: installation

#2280 MNT: remove deprecated Gridliner properties
  lib/cartopy/mpl/gridliner.py
Labels: Component: Gridlines

#2281 Revert "MNT: xfail owslib tests and documentation that use NASA"
  docs/source/conf.py
  lib/cartopy/tests/io/test_ogc_clients.py
  lib/cartopy/tests/mpl/test_caching.py
  lib/cartopy/tests/mpl/test_web_services.py
Labels: Type: Infrastructure
