Repository SciTools/cartopy, pull requests merged in 2023-03, with the labels that each got.

#2096 Oblique Mercator class
  docs/make_projection.py
  lib/cartopy/crs.py
  lib/cartopy/mpl/gridliner.py
  lib/cartopy/tests/crs/test_oblique_mercator.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_ObliqueMercator_default.png
  lib/cartopy/tests/mpl/baseline_images/mpl/test_mpl_integration/test_global_map_ObliqueMercator_rotated.png
  lib/cartopy/tests/mpl/test_mpl_integration.py
Labels: Type: Enhancement, Component: proj, SemVer: minor

#2146 DOC: add omerc to projections list
  docs/source/reference/projections.rst
Labels: Type: Documentation

#2148 add pre-commit.ci badge
  README.md
  docs/source/reference/projections.rst
Labels: Type: Infrastructure

#2155 configure dependabot
  .github/dependabot.yml
Labels: Type: Infrastructure

#2153 pre-commit: adopt codespell hook
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  INSTALL
  docs/source/conf.py
  docs/source/whatsnew/v0.21.rst
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/mpl/ticker.py
  lib/cartopy/tests/mpl/test_feature_artist.py
  lib/cartopy/tests/mpl/test_mpl_integration.py
  lib/cartopy/tests/test_polygon.py
  lib/cartopy/tests/test_vector_transform.py
  pyproject.toml
Labels: Type: Infrastructure

#2151 pre-commit: adopt sort-all hook
  .git-blame-ignore-revs
  .pre-commit-config.yaml
  lib/cartopy/io/shapereader.py
Labels: Type: Infrastructure

#2154 add ci manifest check
  .github/workflows/ci-manifest.yml
  MANIFEST.in
  pyproject.toml
Labels: Type: Infrastructure
