Repository SciTools/cartopy, pull requests merged in 2024-07, with the labels that each got.

#2409 CI: Put release build conditional in the first job to avoid building every time
  .github/workflows/release.yml
Labels: Type: Infrastructure, CI: build wheels

#2407 FIX/MNT: Simplify project geometry handling
  lib/cartopy/crs.py
  lib/cartopy/tests/test_line_string.py
Labels: Component: Geometry transforms

#2414 FIX: contour sticky edges match dataLim
  lib/cartopy/mpl/geoaxes.py
Labels: Type: Bug

#2416 FIX: imshow arguments should be popped before passing upstream
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/test_images.py
Labels: Component: matplotlib
