Repository SciTools/cartopy, pull requests merged in 2024-02, with the labels that each got.

#2306 Preparations for the new v5 SciTools CLA
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Type: Infrastructure

#2323 Make `FeatureArtist` a `Collection`
  lib/cartopy/mpl/feature_artist.py
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/tests/mpl/baseline_images/mpl/test_feature_artist/feature_artist.png
  lib/cartopy/tests/mpl/test_feature_artist.py
  lib/cartopy/tests/mpl/test_gridliner.py
Labels: Type: Enhancement, Component: matplotlib, Component: Feature source

#2332 MNT: Remove wmts-time from expected doc failures
  docs/source/conf.py
Labels: Type: Documentation
