Repository SciTools/cartopy, pull requests merged in 2024-10, with the labels that each got.

#2440 DOC/CI: Prepare for v0.24 release
  .github/workflows/ci-testing.yml
  .github/workflows/release.yml
  docs/make_projection.py
  docs/source/reference/projections.rst
  docs/source/whatsnew/index.rst
  docs/source/whatsnew/v0.24.rst
Labels: Type: Documentation, CI: build wheels

#2452 MNT: Deprecate unused clip_path module
  lib/cartopy/mpl/clip_path.py
Labels: Type: Infrastructure

#2456 DOC: use Matplotlib roles Sphinx extension
  docs/source/conf.py
Labels: Type: Documentation

#2453 MNT: Switch to (lon, lat) for all argument and return ordering
  lib/cartopy/feature/nightshade.py
  lib/cartopy/tests/crs/test_gnomonic.py
  lib/cartopy/tests/crs/test_orthographic.py
  lib/cartopy/tests/feature/test_nightshade.py
  lib/cartopy/tests/test_crs.py
Labels: Type: Infrastructure

#2455 Introduce `path_to_shapely` and `shapely_to_path`
  .github/workflows/ci-testing.yml
  INSTALL
  docs/source/reference/matplotlib.rst
  docs/source/whatsnew/index.rst
  docs/source/whatsnew/v0.25.rst
  environment.yml
  lib/cartopy/crs.py
  lib/cartopy/mpl/feature_artist.py
  lib/cartopy/mpl/geoaxes.py
  lib/cartopy/mpl/patch.py
  lib/cartopy/mpl/path.py
  lib/cartopy/tests/mpl/__init__.py
  lib/cartopy/tests/mpl/test_caching.py
  lib/cartopy/tests/mpl/test_patch.py
  lib/cartopy/tests/mpl/test_path.py
  lib/cartopy/tests/mpl/test_shapely_to_mpl.py
  lib/cartopy/tests/test_linear_ring.py
  pyproject.toml
Labels: Component: Geometry transforms, API Change
