Repository SciTools/cartopy, pull requests merged in 2024-11, with the labels that each got.

#2461 FIX: Add half-pixel shift to img_transform y coordinate
  lib/cartopy/img_transform.py
  lib/cartopy/tests/mpl/test_images.py
  lib/cartopy/tests/test_img_transform.py
Labels: Type: Bug, Component: Geometry transforms, Component: Raster source

#2471 DOC: add deprecation note for `clip_path` module
  docs/source/whatsnew/v0.25.rst
Labels: Type: Documentation

#2470 FIX: create a single inverted polygon when no exteriors found
  lib/cartopy/crs.py
  lib/cartopy/tests/test_polygon.py
Labels: Type: Bug, Component: Geometry transforms
