Repository SciTools/cartopy, pull requests merged in 2024-04, with the labels that each got.

#2365 MNT: xfail deprecated Google Image Tile API
  lib/cartopy/tests/test_img_tiles.py
Labels: Type: Infrastructure

#2366 BLD: Use numpy2.0.0rc1 to build the package
  pyproject.toml
Labels: Type: Infrastructure, CI: build wheels

#2346 DOC: Add whatsnew entry for v0.23
  docs/source/whatsnew/index.rst
  docs/source/whatsnew/v0.23.rst
Labels: Type: Documentation

#2378 Fix incorrect internal use of PlateCarree
  lib/cartopy/crs.py
  lib/cartopy/tests/crs/test_lambert_conformal.py
Labels: Type: Bug, Component: proj

#2376 CI: add scheduled testing against nightlies
  .github/workflows/ci-testing.yml
Labels: Type: Infrastructure
